io.ilardi.systems.AppContext.appMode=DEV
io.ilardi.systems.AppContext.tempDir=/Users/robert.ilardi/tmp

io.ilardi.systems.programLoader.programNameList=MetaCognitionDaemon

io.ilardi.systems.programLoader.programConfig.MetaCognitionDaemon.programClassname=io.ilardi.quinn.mcd.MetaCognitionDaemon


